Update for 1.12.2
Guichaguri/TickrateChanger pull request #5
Opened 2017-09-20 15:02 UTC by cosmicdan

Also a couple other tiny improvements

2017-09-20 17:10 UTC, Guichaguri requested changes

2017-09-20 17:10 UTC, Guichaguri commented on src/main/java/me/guichaguri/tickratechanger/TickrateChanger.java
> +    private static final TickrateChanger INSTANCE = new TickrateChanger();
Why do you initialize it here? Forge already creates an instance

2017-09-20 17:10 UTC, Guichaguri commented on build.gradle
> +    }
Can you fix the indentation here?

2017-09-21 06:12 UTC, cosmicdan commented
Done.

I changed TickrateChanger to an explicit singleton because I was getting an NPE crash on that INSTANCE field - but now I realize it was because I was missing that coremod arg on my run configuration :)

2017-09-21 23:13 UTC, Guichaguri approved these changes

2017-09-21 23:13 UTC, Guichaguri commented
Thank you :)

2017-09-21 23:13 UTC, merged